import HeroSection from "@/components/HeroSection";
import Image from "next/image";

export default function Home() {
  return (
    <section className=" px-6">
      <HeroSection/>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum facere quasi animi suscipit ab, ex ipsum. At itaque dolorem alias adipisci quam a facere nemo laudantium labore totam eum perferendis temporibus architecto obcaecati, magnam deleniti neque earum repellendus nobis, eveniet cum quia, iste velit? Autem ab eligendi quam officiis, facilis accusantium eum temporibus perspiciatis suscipit! Asperiores enim, quo id fuga pariatur adipisci minima cumque amet modi. Accusantium doloremque repudiandae laboriosam possimus architecto quis ratione impedit, culpa fugiat explicabo veritatis accusamus nulla deserunt optio, dolor minima illum! Saepe debitis, esse quos nihil voluptatum autem nulla, ipsum unde placeat in, provident possimus?</p>
    </section>
  );
}
